apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
    containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /home/vagrant/certs/registry.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /home/vagrant/certs/registry.key
        imagePullPolicy: Always
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - name: cert-dir
          mountPath: /home/vagrant/certs
        ports:
        - containerPort: 5000
          hostPort: 5000
    volumes:
    - name: image-store
      emptyDir: {}
    - name: cert-dir
      secret:
        secretName: registry-tls-secret